package com.qurb

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import uniffi.qurb_mobile.KeyStore
import uniffi.qurb_mobile.QurbException
import java.security.KeyStore as JavaKeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The master key, kept where the operating system can protect it.
 *
 * `qurb-mobile` deliberately does not implement this: the Android Keystore is a
 * Java API needing a `Context`, and is not reachable from Rust. See
 * `docs/decisions/0021-the-platform-supplies-the-keystore.md`.
 *
 * Two layers, because the Keystore does not store arbitrary bytes. It holds
 * *keys* and performs operations with them, so:
 *
 *  - a 256-bit AES key lives in the Keystore, generated once, never exported —
 *    on a device with a secure element it never enters this process at all;
 *  - the 32-byte master key is encrypted under it and the ciphertext goes in
 *    ordinary SharedPreferences, where it is useless on its own.
 *
 * Reading the app's data directory therefore yields nothing. Decrypting needs
 * the Keystore, which needs this app's identity, on this device.
 *
 * `setUserAuthenticationRequired` is deliberately **not** set. It would demand
 * a fingerprint every time the key is touched, including during a background
 * sync when nobody is holding the phone, and sync would simply stop happening.
 */
class AndroidKeyStore(context: Context) : KeyStore {

    private val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    override fun put(label: String, secret: ByteArray) {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())

            // The IV is generated by the cipher rather than chosen here, and
            // stored alongside. Reusing an IV with GCM is catastrophic, and the
            // usual way that happens is someone deciding to pick one.
            val iv = cipher.iv
            val sealed = cipher.doFinal(secret)

            prefs.edit()
                .putString(ivKey(label), Base64.encodeToString(iv, Base64.NO_WRAP))
                .putString(label, Base64.encodeToString(sealed, Base64.NO_WRAP))
                .commit()
        } catch (e: Exception) {
            // Wrapped rather than propagated: this crosses an FFI boundary, and
            // an exception that escapes into Rust is undefined behaviour.
            throw QurbException.Other("could not write to the keystore: ${e.message}")
        }
    }

    override fun get(label: String): ByteArray? {
        val sealed = prefs.getString(label, null) ?: return null
        val iv = prefs.getString(ivKey(label), null) ?: return null

        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                wrappingKey(),
                GCMParameterSpec(TAG_BITS, Base64.decode(iv, Base64.NO_WRAP)),
            )
            cipher.doFinal(Base64.decode(sealed, Base64.NO_WRAP))
        } catch (e: Exception) {
            // Distinct from "nothing stored", which returns null. Something IS
            // stored and cannot be read — the Keystore key was invalidated, or
            // the data was restored from another device. Reporting it as absent
            // would look like a fresh install and lose the user's files.
            throw QurbException.Other("the stored key could not be decrypted: ${e.message}")
        }
    }

    override fun remove(label: String) {
        prefs.edit().remove(label).remove(ivKey(label)).commit()
    }

    /** The Keystore-held key that wraps the master key, created on first use. */
    private fun wrappingKey(): SecretKey {
        val keystore = JavaKeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keystore.getEntry(WRAPPING_ALIAS, null) as? JavaKeyStore.SecretKeyEntry)
            ?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                WRAPPING_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun ivKey(label: String) = "$label.iv"

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val PREFS = "qurb-keys"
        const val WRAPPING_ALIAS = "qurb-master-wrapping-key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_BITS = 128
    }
}
