#!/usr/bin/env node
// Write components/icon-paths.ts: the Lucide icons the site uses, taken from
// the desktop window's own sprite (crates/desktop/ui/icons.js), so the site
// and the app draw exactly the same icons. To add one, add its name below --
// and, if the window does not have it yet, to scripts/desktop-icons.py first.
//
//     node scripts/icons.mjs

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const NAMES = `
  house folder folder-open monitor-smartphone hard-drive lock-keyhole settings
  send check arrow-up-down laptop smartphone monitor file file-text file-image
  file-video cloud cloud-off download git-compare trash-2 rotate-ccw shield-check
  key-round chevron-right arrow-right circle-check clock triangle-alert
  refresh-cw history upload external-link plus qr-code bell search wifi-off info
`.split(/\s+/).filter(Boolean)

const here = (path) => fileURLToPath(new URL(path, import.meta.url))
const sprite = readFileSync(here('../../crates/desktop/ui/icons.js'), 'utf8')

const icons = {}
for (const name of NAMES) {
  const found = sprite.match(new RegExp(`<symbol id="i-${name}" viewBox="0 0 24 24">(.*?)</symbol>`))
  if (!found) throw new Error(`${name} is not in the window's sprite; add it to scripts/desktop-icons.py`)
  icons[name] = found[1].replace(/\s*\/>/g, '/>').replace(/>\s+</g, '><').trim()
}

const out = `// Generated by scripts/icons.mjs from crates/desktop/ui/icons.js. Do not edit;
// add the name to that script's list and run it again.
//
// Lucide, ISC License, Copyright (c) Lucide Icons and Contributors:
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.

export const icons = {
${Object.entries(icons).map(([name, body]) => `  '${name}': '${body}'`).join(',\n')}
} as const

export type IconName = keyof typeof icons
`
writeFileSync(here('../components/icon-paths.ts'), out)
console.log(`${Object.keys(icons).length} icons`)
