#!/usr/bin/env python3
"""Write crates/desktop/ui/icons.js from the Lucide icons the window uses.

The window shows Lucide icons (docs/design/direction.md §10), and only the ones
named below: bundling the whole set would be 2,000 icons for 60. The output is
a script that puts an inline SVG sprite into the page, so markup can say
<svg class="i"><use href="#i-house"/></svg> with nothing fetched -- the
window's CSP allows only its own files, and an in-document reference is not a
fetch at all.

    npm pack lucide-static && tar -xzf lucide-static-*.tgz
    ./scripts/desktop-icons.py package

Lucide is ISC-licensed; its notice travels in the generated file.
"""

import re
import sys
from pathlib import Path

# Every icon the window draws. Adding one here and running the script is the
# whole procedure; the names are Lucide's.
ICONS = """
    house folder folder-open file file-text file-image file-video file-audio
    file-archive file-code monitor-smartphone hard-drive settings send
    arrow-up-down lock-keyhole search arrow-left ellipsis download cloud-off
    cloud check git-compare trash-2 clock rotate-ccw triangle-alert
    circle-alert x chevron-right chevron-down laptop smartphone monitor upload
    external-link folder-search key-round bell palette sliders-horizontal
    shield qr-code keyboard power refresh-cw wifi-off pencil copy arrow-right
    circle-check info plus shield-check history user-plus fingerprint users
    eye-off
""".split()

OUT = Path(__file__).resolve().parent.parent / "crates/desktop/ui/icons.js"


def body(svg: str) -> str:
    """The drawing inside an icon's <svg>, attributes left to the page's CSS."""
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    return " ".join(line.strip() for line in inner.strip().splitlines())


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    package = Path(sys.argv[1])
    version = re.search(r'"version":\s*"([^"]+)"', (package / "package.json").read_text()).group(1)
    symbols = []
    for name in ICONS:
        svg = (package / "icons" / f"{name}.svg").read_text()
        symbols.append(f'<symbol id="i-{name}" viewBox="0 0 24 24">{body(svg)}</symbol>')

    sprite = "".join(symbols).replace("\\", "\\\\").replace("`", "\\`")
    OUT.write_text(
        "// Generated by scripts/desktop-icons.py from lucide-static "
        f"{version}. Do not edit;\n"
        "// add the name to that script's list and run it again.\n"
        "//\n"
        "// Lucide, ISC License, Copyright (c) Lucide Icons and Contributors:\n"
        "// Permission to use, copy, modify, and/or distribute this software for any\n"
        "// purpose with or without fee is hereby granted, provided that the above\n"
        "// copyright notice and this permission notice appear in all copies.\n"
        "document.body.insertAdjacentHTML(\n"
        '  "afterbegin",\n'
        '  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">'
        f"{sprite}</svg>`,\n"
        ");\n"
    )
    print(f"wrote {OUT} with {len(ICONS)} icons")


if __name__ == "__main__":
    main()
